// <auto-generated>

#include <mono-wasi/driver.h>
#include <assert.h>
#include <string.h>

MonoClass* mono_get_byte_class(void);
MonoDomain* mono_get_root_domain(void);

MonoArray* mono_wasm_typed_array_new(void* arr, int length) {
    MonoClass* typeClass = mono_get_byte_class();
    MonoArray* buffer = mono_array_new(mono_get_root_domain(), typeClass, length);
    memcpy(mono_array_addr_with_size(buffer, 1, 0), arr, length);
    return buffer;
}

__attribute__((__import_module__("env"), __import_name__("hello")))
extern void __wasm_import_env_hello();

MonoMethod* method_HelloFrom;
MonoMethod* method_StringParam;


__attribute__((export_name("hello")))
void __wasm_export_hello_from() {
    if(!method_HelloFrom) {
        method_HelloFrom = lookup_dotnet_method("SourceGenExample.dll", "ConsoleApp", "Program", "HelloFrom", -1);
        assert(method_HelloFrom);
    }
    
    

    MonoObject* exception;
    void* method_params[] = {  };
    MonoObject* res = mono_wasm_invoke_method(method_HelloFrom, NULL, method_params, &exception);
    assert(!exception);

    

    return res;
}

__attribute__((export_name("string_param")))
void __wasm_export_string_param(char* name) {
    if(!method_StringParam) {
        method_StringParam = lookup_dotnet_method("SourceGenExample.dll", "ConsoleApp", "Program", "StringParam", -1);
        assert(method_StringParam);
    }
    
    MonoString* name_trans = mono_wasm_string_from_js(name);

    MonoObject* exception;
    void* method_params[] = { name_trans };
    MonoObject* res = mono_wasm_invoke_method(method_StringParam, NULL, method_params, &exception);
    assert(!exception);

    free(name);

    return res;
}

void fake_settimeout(int timeout) {
    //
}

void attach_internal_calls() {
    mono_add_internal_call("System.Threading.TimerQueue::SetTimeout", fake_settimeout);
    mono_add_internal_call("ConsoleApp.Interop::Hello", __wasm_import_hello);
}

