// <auto-generated>
#include <mono-wasi/driver.h>
#include <assert.h>
#include <string.h>

MonoClass* mono_get_byte_class(void);
MonoDomain* mono_get_root_domain(void);

MonoArray* mono_wasm_typed_array_new(void* arr, int length) {
    MonoClass* typeClass = mono_get_byte_class();
    MonoArray* buffer = mono_array_new(mono_get_root_domain(), typeClass, length);
    memcpy(mono_array_addr_with_size(buffer, 1, 0), arr, length);
    return buffer;
}

__attribute__((__import_module__("env"), __import_name__("hello")))
extern void __wasm_import_env_hello();

MonoMethod* method_ArrayParam;


__attribute__((export_name("array_param")))
MonoObject* __wasm_export_array_param(char* name,void* nrs_ptr, int nrs_len) {
    if(!method_ArrayParam) {
        method_ArrayParam = lookup_dotnet_method("guest.dll", "guest", "Program", "ArrayParam", -1);
        assert(method_ArrayParam);
    }
    MonoString* name_trans = mono_wasm_string_from_js(name);
	MonoArray* nrs_trans = nrs_ptr ? mono_wasm_typed_array_new(nrs_ptr, nrs_len) : NULL;
    MonoObject* exception;
    void* method_params[] = { name_trans,nrs_trans };
    MonoObject* res = mono_wasm_invoke_method(method_ArrayParam, NULL, method_params, &exception);
    assert(!exception);
    free(name);
    return res;
}

void fake_settimeout(int timeout) {
    //
}

void attach_internal_calls() {
    mono_add_internal_call("System.Threading.TimerQueue::SetTimeout", fake_settimeout);
    mono_add_internal_call("guest.Interop::Hello", __wasm_import_env_hello);
}
