// <auto-generated>
#include <mono-wasi/driver.h>
#include <assert.h>
#include <string.h>

MonoClass* mono_get_byte_class(void);
MonoDomain* mono_get_root_domain(void);

MonoArray* mono_wasm_typed_array_new(void* arr, int length) {
    MonoClass* typeClass = mono_get_byte_class();
    MonoArray* buffer = mono_array_new(mono_get_root_domain(), typeClass, length);
    memcpy(mono_array_addr_with_size(buffer, 1, 0), arr, length);
    return buffer;
}

__attribute__((__import_module__("env"), __import_name__("hello")))
extern void __wasm_import_env_hello();
__attribute__((__import_module__("env"), __import_name__("make_other_class")))
extern void __wasm_import_env_make_other_class(MonoObject*);

MonoMethod* method_HelloFrom;
MonoMethod* method_StringParam;
MonoMethod* method_ArrayParam;
MonoMethod* method_ObjectImportParam;
MonoMethod* method_Hello;
MonoMethod* method_ThisContext;


__attribute__((export_name("hello")))
MonoObject* __wasm_export_hello_from() {
    if(!method_HelloFrom) {
        method_HelloFrom = lookup_dotnet_method("guest.dll", "guest", "Program", "HelloFrom", -1);
        assert(method_HelloFrom);
    }
    
    MonoObject* exception;
    void* method_params[] = {  };
    MonoObject* res = mono_wasm_invoke_method(method_HelloFrom, NULL, method_params, &exception);
    assert(!exception);
    
    return res;
}

__attribute__((export_name("string_param")))
MonoObject* __wasm_export_string_param(char* name) {
    if(!method_StringParam) {
        method_StringParam = lookup_dotnet_method("guest.dll", "guest", "Program", "StringParam", -1);
        assert(method_StringParam);
    }
    MonoString* name_trans = mono_wasm_string_from_js(name);
    MonoObject* exception;
    void* method_params[] = { name_trans };
    MonoObject* res = mono_wasm_invoke_method(method_StringParam, NULL, method_params, &exception);
    assert(!exception);
    free(name);
    return res;
}

__attribute__((export_name("array_param")))
MonoObject* __wasm_export_array_param(char* name,void* nrs_ptr, int nrs_len) {
    if(!method_ArrayParam) {
        method_ArrayParam = lookup_dotnet_method("guest.dll", "guest", "Program", "ArrayParam", -1);
        assert(method_ArrayParam);
    }
    MonoString* name_trans = mono_wasm_string_from_js(name);
	MonoArray* nrs_trans = nrs_ptr ? mono_wasm_typed_array_new(nrs_ptr, nrs_len) : NULL;
    MonoObject* exception;
    void* method_params[] = { name_trans,nrs_trans };
    MonoObject* res = mono_wasm_invoke_method(method_ArrayParam, NULL, method_params, &exception);
    assert(!exception);
    free(name);
    return res;
}

__attribute__((export_name("object_import_param")))
MonoObject* __wasm_export_object_import_param() {
    if(!method_ObjectImportParam) {
        method_ObjectImportParam = lookup_dotnet_method("guest.dll", "guest", "Program", "ObjectImportParam", -1);
        assert(method_ObjectImportParam);
    }
    
    MonoObject* exception;
    void* method_params[] = {  };
    MonoObject* res = mono_wasm_invoke_method(method_ObjectImportParam, NULL, method_params, &exception);
    assert(!exception);
    
    return res;
}

__attribute__((export_name("class_hello")))
MonoObject* __wasm_export_hello(MonoObject* dotnet_target_instance) {
    if(!method_Hello) {
        method_Hello = lookup_dotnet_method("guest.dll", "guest", "OtherClass", "Hello", -1);
        assert(method_Hello);
    }
    
    MonoObject* exception;
    void* method_params[] = {  };
    MonoObject* res = mono_wasm_invoke_method(method_Hello, dotnet_target_instance, method_params, &exception);
    assert(!exception);
    
    return res;
}

__attribute__((export_name("this_context")))
MonoObject* __wasm_export_this_context(MonoObject* dotnet_target_instance,char* name) {
    if(!method_ThisContext) {
        method_ThisContext = lookup_dotnet_method("guest.dll", "guest", "OtherClass", "ThisContext", -1);
        assert(method_ThisContext);
    }
    MonoString* name_trans = mono_wasm_string_from_js(name);
    MonoObject* exception;
    void* method_params[] = { name_trans };
    MonoObject* res = mono_wasm_invoke_method(method_ThisContext, dotnet_target_instance, method_params, &exception);
    assert(!exception);
    free(name);
    return res;
}

void fake_settimeout(int timeout) {
    //
}

void attach_internal_calls() {
    mono_add_internal_call("System.Threading.TimerQueue::SetTimeout", fake_settimeout);
    mono_add_internal_call("guest.Interop::Hello", __wasm_import_env_hello);
	mono_add_internal_call("guest.Interop::MakeOtherClass", __wasm_import_env_make_other_class);
}
